INSERT INTO stadiums (name, country, city, capacity)
VALUES 
('Old Trafford', 'England', 'Greater Manchester', 76962),
('Camp Nou', 'Spain', 'Barcelona', 99354),
('Allianz Arena', 'Germany', 'Munich', 75000),
('San Siro', 'Italy', 'Milan', 80018),
('Parc des Princes', 'France', 'Paris', 48712),
('Johan Cruijff Arena', 'Netherlands', 'Amsterdam', 54851),
('Estádio da Luz', 'Portugal', 'Lisbon', 64715),
('Luzhniki Stadium', 'Russia', 'Moscow', 81000),
('Maracanã', 'Brazil', 'Rio de Janeiro', 78838),
('La Bombonera', 'Argentina', 'Buenos Aires', 54461),
('Anfield', 'England', 'Liverpool', 53394),
('Signal Iduna Park', 'Germany', 'Dortmund', 81365),
('Giuseppe Meazza', 'Italy', 'Milan', 80018),
('Stade Vélodrome', 'France', 'Marseille', 67730),
('FNB Stadium', 'South Africa', 'Johannesburg', 94736),
('Emirates Stadium', 'England', 'London', 60260),
('Estadio Azteca', 'Mexico', 'Mexico City', 87000),
('Wembley Stadium', 'England', 'London', 90000),
('Santiago Bernabéu', 'Spain', 'Madrid', 81044),
('Mercedes-Benz Stadium', 'United States', 'Atlanta', 42000);

INSERT INTO stadiums (name, country, city, capacity)
VALUES 
('Parc Olympique Lyonnais', 'France', 'Lyon', 59186),
('Stade Geoffroy-Guichard', 'France', 'Saint-Étienne', 41965),
('Parc des Princes', 'France', 'Paris', 48712),
('Stade Vélodrome', 'France', 'Marseille', 67730),
('Stade Pierre-Mauroy', 'France', 'Lille', 50000),
('Roazhon Park', 'France', 'Rennes', 29755),
('Stade de la Mosson', 'France', 'Montpellier', 25500),
('Stade de Reims', 'France', 'Reims', 21094),
('Stade Bollaert-Delelis', 'France', 'Lens', 38322),
('Stade Auguste-Delaune', 'France', 'Reims', 21504),
('Stade Louis II', 'Monaco', 'Monaco', 18523),
('Stade de la Beaujoire', 'France', 'Nantes', 35261),
('Stade du Moustoir', 'France', 'Lorient', 18523),
('Stade Gaston Gérard', 'France', 'Dijon', 15739),
('Stade Saint-Symphorien', 'France', 'Metz', 25138),
('Stade Francis-Le Blé', 'France', 'Brest', 15983),
('Stade des Costières', 'France', 'Nîmes', 18240),
('Stade Bonal', 'France', 'Montbéliard', 20457),
('Stade de la Meinau', 'France', 'Strasbourg', 26109),
('Stade Michel d Ornano', 'France', 'Caen', 21591),
('Old Trafford', 'England', 'Manchester', 74879),
('Anfield', 'England', 'Liverpool', 53394),
('Emirates Stadium', 'England', 'London', 60260),
('Etihad Stadium', 'England', 'Manchester', 53097),
('Stamford Bridge', 'England', 'London', 40834),
('Tottenham Hotspur Stadium', 'England', 'London', 62062),
('King Power Stadium', 'England', 'Leicester', 32312),
('Goodison Park', 'England', 'Liverpool', 39958),
('Molineux Stadium', 'England', 'Wolverhampton', 32050),
('St James Park', 'England', 'Newcastle', 52305),
('Elland Road', 'England', 'Leeds', 40000),
('Craven Cottage', 'England', 'London', 19760),
('Villa Park', 'England', 'Birmingham', 42130),
('Amex Stadium', 'England', 'Brighton', 30750),
('Selhurst Park', 'England', 'London', 25456),
('Dean Court', 'England', 'Bournemouth', 11364),
('Bramall Lane', 'England', 'Sheffield', 32702),
('St Marys Stadium', 'England', 'Southampton', 32384),
('London Stadium', 'England', 'London', 60000),
('The Hawthorns', 'England', 'West Bromwich', 26688),
('Camp Nou', 'Spain', 'Barcelona', 99354),
('Santiago Bernabéu', 'Spain', 'Madrid', 81044),
('Wanda Metropolitano', 'Spain', 'Madrid', 68680),
('Estadio Ramón Sánchez-Pizjuán', 'Spain', 'Seville', 43878),
('Mestalla', 'Spain', 'Valencia', 55000),
('San Mamés', 'Spain', 'Bilbao', 53289),
('Estadio de la Cerámica', 'Spain', 'Villarreal', 23500),
('Benito Villamarín', 'Spain', 'Seville', 60721),
('Estadi Ciutat de València', 'Spain', 'Valencia', 25411),
('Estadio José Zorrilla', 'Spain', 'Valladolid', 27209),
('Abanca-Balaídos', 'Spain', 'Vigo', 29955),
('El Sadar', 'Spain', 'Pamplona', 23829),
('Coliseum Alfonso Pérez', 'Spain', 'Getafe', 17393),
('RCDE Stadium', 'Spain', 'Barcelona', 40224),
('Estadio de Mendizorroza', 'Spain', 'Vitoria-Gasteiz', 19840),
('Iberostar Stadium', 'Spain', 'Palma', 23056),
('Estadio José Alvalade', 'Spain', 'Lisbon', 52301),
('Ciudad de Valencia', 'Spain', 'Valencia', 25354),
('Nuevo Los Cármenes', 'Spain', 'Granada', 19350),
('Estadio El Alcoraz', 'Spain', 'Huesca', 7638),
('Allianz Arena', 'Germany', 'Munich', 75000),
('Signal Iduna Park', 'Germany', 'Dortmund', 81365),
('Mercedes-Benz Arena', 'Germany', 'Stuttgart', 60449),
('Red Bull Arena', 'Germany', 'Leipzig', 42959),
('Volkswagen Arena', 'Germany', 'Wolfsburg', 30000),
('BayArena', 'Germany', 'Leverkusen', 30210),
('Commerzbank-Arena', 'Germany', 'Frankfurt', 51500),
('Opel Arena', 'Germany', 'Mainz', 34034),
('PreZero Arena', 'Germany', 'Sinsheim', 30150),
('WWK Arena', 'Germany', 'Augsburg', 30660),
('Olympiastadion', 'Germany', 'Berlin', 74750),
('RheinEnergieStadion', 'Germany', 'Cologne', 50076),
('Borussia-Park', 'Germany', 'Mönchengladbach', 54600),
('Schwarzwald-Stadion', 'Germany', 'Freiburg', 24000),
('Audi Sportpark', 'Germany', 'Ingolstadt', 15124),
('Wohninvest Weserstadion', 'Germany', 'Bremen', 42100),
('Max-Morlock-Stadion', 'Germany', 'Nuremberg', 50000),
('Mercedes-Benz Arena', 'Germany', 'Stuttgart', 60449),
('Veltins-Arena', 'Germany', 'Gelsenkirchen', 62271),
('Opel Arena', 'Germany', 'Mainz', 34034);
INSERT INTO stadiums (name, country, city, capacity)
VALUES 
('San Siro', 'Italy', 'Milan', 80018),
('Allianz Stadium', 'Italy', 'Turin', 41913),
('Stadio Olimpico', 'Italy', 'Rome', 72698),
('Stadio San Paolo', 'Italy', 'Naples', 60240),
('Stadio Artemio Franchi', 'Italy', 'Florence', 43204),
('Stadio Luigi Ferraris', 'Italy', 'Genoa', 36900),
('Stadio Marcantonio Bentegodi', 'Italy', 'Verona', 39350),
('Stadio Friuli', 'Italy', 'Udine', 25952),
('Stadio Ennio Tardini', 'Italy', 'Parma', 27000),
('Stadio Luigi Ferraris', 'Italy', 'Genoa', 36900),
('Stadio Renato Dall Ara', 'Italy', 'Bologna', 38179),
('Stadio Comunale di Torino', 'Italy', 'Turin', 27994),
('Stadio Ciro Vigorito', 'Italy', 'Benevento', 25000),
('Stadio Via del Mare', 'Italy', 'Lecce', 40850),
('Stadio Mario Rigamonti', 'Italy', 'Brescia', 16045),
('Stadio Paolo Mazza', 'Italy', 'Ferrara', 16145),
('Stadio Olimpico Grande Torino', 'Italy', 'Turin', 27994),
('Stadio Artemio Franchi', 'Italy', 'Siena', 15395),
('Stadio Sant Elia', 'Italy', 'Cagliari', 16012),
('Stadio Ezio Scida', 'Italy', 'Crotone', 16365);

-- Buat fungsi di bawah untuk menghapus data stadium yang sama
CREATE OR REPLACE FUNCTION delete_same_stadium()
RETURNS VOID AS $$
BEGIN
   
    DELETE FROM stadiums s1
    USING stadiums s2
    WHERE s1.stadium_id <> s2.stadium_id AND s1.name = s2.name AND s1.stadium_id > s2.stadium_id;
   
    RETURN;
END;
$$ LANGUAGE plpgsql;

-- Lalu Jalankan fungsi nya
select delete_same_stadium();